### ISSUE TITLE
返回结果是 SingleLife  而不是 Single，是不是意味着就要放弃 RxKotlin 这个库

### ISSUE THREAD

**Issue by ivotai** [liujingxing/RxLife#10]
https://github.com/ReactiveX/RxKotlin

**Comment by liujingxing** [comment]
对于Rxlife而言，在执行`Rxlife.to`或者`Rxlife.as`后，我们仅能执行订阅回调操作，这样才能做到从下往上一层层的断开管道，从而避免内存泄露，如果下游还有其它非订阅操作，就依然有可能会造成内存泄露，这就是为啥`返回结果是 SingleLife 而不是 Single`的原因。

对于RxKotlin遇上RxLife，仅仅是不能使用订阅相关的api而已，其它不影响。
