### ISSUE TITLE
rxLifeScope.launch {  } 线程选择

### ISSUE THREAD

**Issue by Hwy152** [liujingxing/RxLife#13]
rxLifeScope.launch {  } 可以像 GlobalScope.launch (Dispatchers.IO){  }，可以选择在哪个线程中调用吗？
有时候一些操作必须要到IO线程才能操作

**Comment by liujingxing** [comment]
暂时不支持，可以过`withContext`方法切换线程，如下：
```
rxLifeScope.launch {              
    withContext(Dispatchers.IO) {
        //IO线程执行                 
    }                            
}                                
```

**Comment by Hwy152** [comment]
上面的方式，AndroidStudio withContext代码块里面还是报黄
现在我用的是RxJava的方式
Observable.just(Any()).observeOn(Schedulers.io()).life(this).subscribe {

}

**Comment by liujingxing** [comment]
withContext代码块报黄是kotlin编译器的bug，加个注解消除警告就好了
