### ISSUE TITLE
demo中的observableByVM点击事件崩溃了

### ISSUE THREAD

**Issue by mycrossroads** [liujingxing/RxLife#15]
fun observableByVM(view: View) {
        //注:不能使用new 关键字创建MyViewModel对象，否则MyViewModel感知不到生命周期
        val viewModel = ViewModelProvider(this).get(MyViewModel::class.java)
    }
这个崩溃了

**Comment by liujingxing** [comment]
activity版本更新至1.1.0就好了，代码已上传，你再试试
