### ISSUE TITLE
引入最新的rxlife-rxjava2报错

### ISSUE THREAD

**Issue by mycrossroads** [liujingxing/RxLife#16]
rxlife-rxjava2_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.会报这个错误。但是使用implementation 'com.rxjava.rxlife:rxlife-x:1.0.8'就没有问题，求大神指导

**Comment by liujingxing** [comment]
升级kotlin版本即可，可参考https://github.com/liujingxing/rxhttp/issues/251
