### ISSUE TITLE
.life(this)  需要引入什么库吗。为什么敲不出来呀

### ISSUE THREAD

**Issue by qingweiSun** [liujingxing/RxLife#19]

**Comment by liujingxing** [comment]
依赖[RxLife](https://github.com/liujingxing/RxLife)

**Comment by liujingxing** [comment]
不需要，life/lifeOnMain方法是kotlin的扩展方法，Java不能用

**Comment by qingweiSun** [comment]
我是 koltin  但
Observable.intervalRange(1, 100, 0, 200, TimeUnit.MILLISECONDS)
    .life(this)
    .subscribe { aLong ->
        Log.e("LJX", "accept=" + aLong)
    }
直接报错

**Comment by liujingxing** [comment]
？报啥错？
