### ISSUE TITLE
一个命名方面的小问题

### ISSUE THREAD

**Issue by w0080626** [liujingxing/RxLife#2]
当使用kotlin语言开发的时候 as 是关键词，不能作为方法名使用，需要`as`这样使用，不太方便，望改名。

**Comment by liujingxing** [comment]
好的，我已经意识到这个问题，近期会开始kotlin版本开发

**Comment by liujingxing** [comment]
版本已更新，kotlin可使用lifeXXX操作符替换asXXX操作符
