### ISSUE TITLE
ViewModelProvider(this).get(MyViewModel::class.java)

### ISSUE THREAD

**Issue by d8txc** [liujingxing/RxLife#21]
//注:不能使用new 关键字创建MyViewModel对象，否则MyViewModel感知不到生命周期
val viewModel = ViewModelProvider(this).get(MyViewModel::class.java)
大神请教，viewModel的创建，在kt下如上写法，在java下必须要new，上述说不能使用new，请问java下viewModel如何创建？

**Comment by liujingxing** [comment]
我的意思是不能`new MyViewModel()`，`ViewModelProvider` Java的话该怎样就怎样

**Comment by d8txc** [comment]
OK, 明白了，文件理解有误，谢谢大神解答！
