### ISSUE TITLE
在用, 经测试没问题,但是有一个小问题

### ISSUE THREAD

**Issue by zzh1026** [liujingxing/RxLife#4]
在使用的过程中使用as方法转换后返回ObservableLife对象然后调用subscribe方法,这样的流程可以走得通,但是这样导致了扩展性的限制, 我在实际使用中想把这个方法抽取到网络请求的公共方法中,这样对代码的侵入性会很低,但是由于调用该方法之后只能 subscribe 导致将这个方法抽取比较复杂了, 所以我想问一下为什么不能返回 Observable 对象方便向下调用呢?

**Comment by liujingxing** [comment]
RxLife我在https://juejin.im/post/5cf3e1235188251c064815f1一文中介绍了其原理。使用as操作符后，下游除订阅事件外，不能做其它事情，否则就可能造成RxLife不能正常工作。这是RxJava自身的设计原则，必须要拿到最底层的Disposable对象，才能将上下游中断。

**Comment by liujingxing** [comment]
RxLife我在https://juejin.im/post/5cf3e1235188251c064815f1一文中介绍了其原理。
使用as操作符后，下游除订阅事件外，不能做其它事情，否则就可能造成RxLife不能正常工作。这是RxJava自身的设计原则，必须要拿到最底层的Disposable对象，才能将上下游中断。

**Comment by liujingxing** [comment]
RxLife我在https://juejin.im/post/5cf3e1235188251c064815f1

一文中介绍了其原理。使用as操作符后，下游除订阅事件外，不能做其它事情，否则就可能造成RxLife不能正常工作。这是RxJava自身的设计原则，必须要拿到最底层的Disposable对象，才能将上下游中断。
