### ISSUE TITLE
Rxlife的BaseScope不支持Service？目前项目中，会在服务里也会用到Rxjava

### ISSUE THREAD

**Issue by 1Patience-and-1careful** [liujingxing/RxLife#6]

**Comment by liujingxing** [comment]
这个暂时不支持，只能订阅后拿到Disposable对象，然后手动关闭

**Comment by liujingxing** [comment]
对于Androidx项目，依赖`androidx.lifecycle:lifecycle-service:x.x.x`
非Androidx项目，依赖`android.arch.lifecycle:extensions:x.x.x`，随后`Service`继承`LifecycleService`，就可直接使用`RxLife`自动关闭请求
