### ISSUE TITLE
在View中是否无法使用   

### ISSUE THREAD

**Issue by Liangwenb** [liujingxing/RxLife#7]
Observable
                .interval(delay, peroid, TimeUnit.MILLISECONDS)
                .as(RxLife.as(this))
                .subscribe(aLong -> {
                         ........
                });
会不执行

**Comment by liujingxing** [comment]
View还未添加到窗口时，会走异常回调；你可以`.as(Rxlife.as(this, true))`传入true，忽略View是否添加到窗口

**Comment by Liangwenb** [comment]
谢谢。 没注意到这个细节问题。
