### ISSUE TITLE
rxjava3中的Observable位于其core包下

### ISSUE THREAD

**Issue by zzh1026** [liujingxing/RxLife#9]
使用rxjava3发现 Observable 没有as方法

**Comment by liujingxing** [comment]
RxJava3删除了as方法，用to方法替代，如：`to(RxLife.to(this))、to(RxLife.toMain(this))`

**Comment by zzh1026** [comment]
你效率真高, 我刚找到这个方法, 正准备删掉这个issues呢.感谢.
